name: DraconyxPro
version: '1.20.5'
main: fur.kiysohi.draconyxpro.Main
api-version: 1.19
authors: [ MyNameIsKiyoshi ]
description: Block CMDs, TabComplete, F3-Mark and More!!
website: https://github.com/MyNameIsKiyoshi
softdepend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  draconyx:
    description: "DraconyxPRO Super Anti Blocker."
    aliases: [ dx ]
